version: "3.8"

services:

  frontend:
    build: ./
    container_name: jjodel
    volumes:
    - ./src:/app/src
    networks:
      network:
    ports:
      - '3000:3000'
    environment:
      - CHOKIDAR_USEPOLLING=true

volumes:
  db_data:

networks:
  network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
