version: "3.8"

services:
  app:
    container_name: jjodel
    image: jjodel:latest
    volumes:
    - ./src:/app/src
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
