version: "3.8"

services:

  frontend:
    container_name: jjodel
    image: giordanotin/jjodel:2.0
    ports:
      - '3000:3000'
    links:
      - memorec

  memorec:
    container_name: memorec
    image: giordanotin/memorec:1.5
    ports:
      - '8080:8080'
